engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
          python_version: 3
  markdownlint:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3

ratings:
  paths:
  - "**.py"

exclude_paths: []
