gpu_device_id: 1

train:
    epochs: 20
    batch_size: 1024
    train_dir: ./logs/train/
    tfrecord:
        min_after_dequeue: 100
        capacity: ~
        num_threads: 32
        preprocess_level: 1

model:
    model_dir: ./data/models/
    model_path: ./data/models/mnist
